@startuml
class Help {
  Number orden
  String grupo
  String grupoeng
  String pregunta
  String preguntaeng
  String respuesta
  String respuestaeng
  Boolean activo
  Date createdAt
  Date updatedAt
}
@enduml
