@startuml SecuenceAgregarSolicitud
hide footbox

actor Usuario
participant Sistema
Usuario->Sistema: Solicita Administrar Solicitudes
Sistema->Sistema: Consulta base de datos 
Sistema-->Usuario: Devuelve lista de Solicitudes
Usuario->Sistema: Selecciona "Agregar nueva Solicitu"
Sistema->Sistema: Muestra formulario de nuevo solicitud
Usuario->Sistema: Completa formulario y envía datos
Sistema->Sistema: Valida datos del solicitud
alt Datos válidos
  Sistema->Sistema: Almacena nuevo solicitud en la base de datos
  Sistema->Usuario: Confirma agregado exitoso del solicitud
else Datos inválidos
  Sistema->Usuario: Notifica errores en el formulario
end
@enduml
