@startuml ColaboracionSecuenceActualizarSolicitudes
hide footbox

actor "Usuario" as (1)
actor "Sistema" as (2)
actor "Base de Datos" as (3)

1 --> 2 : Solicita actualizar \nuna Solicitud
2 --> 3 : Solicita Datos de la \nSolicitud seleccionada
2 --> 1 : Muestra Datos de \la Solicitud seleccionada
1 --> 2 : Actualiza Datos y \nselecciona Guardar
2 --> 3 : Envía los Datos \nactualizados \nde la Solicitud
3 --> 2 : Confirma resultado de la actualización
2 --> 1 : Notifica resultado \nde la actualización
2 --> 1 : Notifica por mail actualización \nde Solicitud a Proveedores



@enduml
