@startuml ColaboracionSecuenceAgregarProducto
hide footbox

participant "Usuario" as 1
participant "BD" as 2
participant "Sistema" as 3
participant "BaseDeDatos" as 4

1 -> 3: 1. Solicita Administrar Productos
3 -> 2: 2. Consulta base de datos
2 -> 3: 3. Devuelve lista de Productos
3 -> 1: 4. Muestra lista de Productos
1 -> 3: 5. Selecciona "Agregar" nuevo Producto
3 --> 3: 6. Muestra formulario de nuevo Producto
1 -> 3: 7. Completa formulario y selecciona "Guardar"
3 -> 2: 8. Valida datos del nuevo Producto
3 -> 2: 9. Almacena el nuevo Producto en la base de datos
2 -> 3: 10. Confirma almacenamiento exitoso
3 -> 1: 11. Confirma agregado exitoso del Producto
3 -> 1: 12. Notifica errores en el formulario

@enduml
